name: Monitor do Site da Caminhada
on:
  schedule:
    - cron: '*/5 8-19 * * 1' # A cada 5 minutos, apenas à Segunda-feira
  workflow_dispatch: # Permite executar manualmente a partir da interface do GitHub (segunda é 1)
jobs:
  run-checker:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        env:
          GIST_ID: '' # <-- SUBSTITUA PELO ID DO SEU GIST
          GIST_PAT: ${{ secrets.GIST_PAT }} # <-- Lê o secret que configurou (importante ter salvo no github vars)
        shell: pwsh
        run: ./Check-Caminhada.ps1
